title: docking.ai
email: sness@sness.net
description: >- # this means to ignore newlines until "baseurl:"
  docking.ai AI docking
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dockingai
github_username: sness23
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
